services:
  dbservice:
    image: postgres:latest
    container_name: postgres_con
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-admin}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-admin}
      POSTGRES_DB: ${DATABASE_NAME:-mydb}
    volumes:
      # Hardcode binding to project directory to prevent Mac file sharing errors
      - ./postgres-data:/var/lib/postgresql