services:
  dbservice:
    image: postgres:latest
    container_name: postgres_con
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-admin}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-admin}
      POSTGRES_DB: ${DATABASE_NAME:-mydb}
    volumes:
      # Sửa lại thành Bind Mount trỏ đúng vào thư mục /data bên trong container
      - ${POSTGRES_DATA_PATH:-/home/shrimp/code/portgres-db}:/var/lib/postgresql