spring.application.name=ddd

logging.pattern.console=${CONSOLE_LOG_PATTERN:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15})- %cyan(%msg%n)}

spring.jpa.hibernate.ddl-auto=none


#DATABASE-CONNECTION
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:mydb}
spring.datasource.username=${DATABASE_USERNAME:admin}
spring.datasource.password=${DATABASE_PASSWORD:admin}

spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.database-platform= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}
spring.jpa.properties.hibernate.default_batch_fetch_size=${DEFAULT_BATCH_FETCH_SIZE:50}

#---docker---
spring.docker.compose.enabled=true
spring.docker.compose.file=compose.yaml
spring.docker.compose.lifecycle-management=start-only
#spring.docker.compose.lifecycle-management=start_only